### ISSUE TITLE
SDK should be built against a stable LTS version of Java

### ISSUE THREAD

**Issue by alphafoobar** [authsignal/authsignal-java#4]
It seems this SDK is built using Java 16? It would be better to choose a stable LTS version of Java to build against. 

Java 11 would be a good pick, it's out of support from oracle, but continues to be supported by many other Java providers. See: https://en.wikipedia.org/wiki/Java_version_history#Release_table

**Comment by chrisfisher** [comment]
The SDK is now built using Java 17.
